applicationApiVersion: v1beta1

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  glooctlInstaller.image.full:
    type: string
    default: gcr.io/solo-io-public/gloo/installer:1.1
    x-google-marketplace:
      type: IMAGE
  glooImages.gloo.full:
    type: string
    default: gcr.io/solo-io-public/gloo:1.1.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: glooImages.gloo.registry
            repo: glooImages.gloo.repository
            tag: glooImages.gloo.tag
  glooImages.discovery.full:
    type: string
    default: gcr.io/solo-io-public/gloo/discovery:1.1.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: glooImages.discovery.registry
            repo: glooImages.discovery.repository
            tag: glooImages.discovery.tag
  glooImages.gateway.full:
    type: string
    default: gcr.io/solo-io-public/gloo/gateway:1.1.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: glooImages.gateway.registry
            repo: glooImages.gateway.repository
            tag: glooImages.gateway.tag
  glooImages.certgen.full:
    type: string
    default: gcr.io/solo-io-public/gloo/certgen:1.1.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: glooImages.certgen.registry
            repo: glooImages.certgen.repository
            tag: glooImages.certgen.tag
  glooImages.glooEnvoyWrapper.full:
    type: string
    default: gcr.io/solo-io-public/gloo/gloo-envoy-wrapper:1.1.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: glooImages.glooEnvoyWrapper.registry
            repo: glooImages.glooEnvoyWrapper.repository
            tag: glooImages.glooEnvoyWrapper.tag
  glooImages.accessLogger.full:
    type: string
    default: gcr.io/solo-io-public/gloo/access-logger:1.1.0
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: glooImages.accessLogger.registry
            repo: glooImages.accessLogger.repository
            tag: glooImages.accessLogger.tag
# accessible as: {{ .Values.enterpriseLicense }}
  enterpriseLicense:
    type: string
    default: ""
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
# accessible as {{ .Values.enterpriseLicenseEncoded }}
          base64Encoded: enterpriseLicenseEncoded
# the name used here will lowercased and "-" appended to the install name
# ex: operatorServiceAccount would become "test-install-operatorserviceaccount" when installed in .Release.Name="test-install"
  glooctlServiceAccount:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        # - type: ClusterRole        # This is a cluster-wide ClusterRole
        #   rulesType: PREDEFINED
        #   rulesFromRoleName: edit  # Use predefined role named "edit"
        - type: Role               # This is a namespaced Role
          rulesType: CUSTOM        # We specify our own custom RBAC rules
          rules:
            # TODO: populate the rules lists from a separate file so it's easier to reuse and test rule specs
            # for now, give access to everything
          - apiGroups: [""]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["batch"]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["apps"]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["gloo.solo.io"]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["gateway.solo.io"]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["apiextensions.k8s.io/v1beta1"]
            resources: ["*"]
            verbs: ["*"]
          # remove post 1.2
          - apiGroups: ["gateway.solo.io.v2"]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["extensions/v1beta1"]
            resources: ["*"]
            verbs: ["*"]
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: [""]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["apiextensions.k8s.io"]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["rbac.authorization.k8s.io"]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["apiextensions.k8s.io/v1beta1"]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["admissionregistration.k8s.io"]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["extensions/v1beta1"]
            resources: ["*"]
            verbs: ["*"]

required:
- name
- namespace
