applicationApiVersion: v1beta1

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
# accessible as: {{ .Values.enterpriseLicense }}
  enterpriseLicense:
    type: string
    default: ""
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
# accessible as {{ .Values.enterpriseLicenseEncoded }}
          base64Encoded: enterpriseLicenseEncoded

required:
- name
- namespace
