properties:
  # set a default value (need to copy other fields for validation to pass)
  enterpriseLicense:
    type: string
    # without modification, the schema's "default" value is an empty string
    # toggle these lines to force the verification script to use gloo vs. glooE
    # default: ""
    default: "test-schema-license-value"
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: enterpriseLicenseEncoded
