x-google-marketplace:
  # MUST be v2.
  schemaVersion: v2

  # MUST match the version of the Application custom resource object.
  # This is the same as the top level applicationApiVersion field in v1.
  applicationApiVersion: v1beta1

  # The release version is required in the schema and MUST match the
  # release tag on the the deployer.
  publishedVersion: '1.15.14'
  publishedVersionMetadata:
    releaseNote: >-
      Latest release.
    # Setting "recommended" to "true" indicates that users are encouraged
    # to update as soon as possible.
    recommended: true

  # Image declaration is required here.
  images:
    installer:
      properties:
        imageInstallerFull:
          default: gcr.io/solo-io-public/gloo/installer:1.15.14
          type: FULL

# The Properties and Required sections of v2 are structured the same as those of v1.
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  # the name used here will lowercased and "-" appended to the install name
  # ex: operatorServiceAccount would become "test-install-operatorserviceaccount" when installed in .Release.Name="test-install"
  glooctlServiceAccount:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: Service account used by glooctl to install Gloo
        roles:
        - type: Role               # This is a namespaced Role
          rulesType: CUSTOM        # We specify our own custom RBAC rules
          rules:
          - apiGroups: ["app.k8s.io"]
            resources: ["applications"]
            verbs: ["*"]
            # TODO: populate the rules lists from a separate file so it's easier to reuse and test rule specs
            # for now, give access to everything
          - apiGroups: [""]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["batch"]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["apps"]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["gloo.solo.io"]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["gateway.solo.io"]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["apiextensions.k8s.io/v1beta1"]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["extensions"]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["extensions/v1beta1"]
            resources: ["*"]
            verbs: ["*"]
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: [""]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["apiextensions.k8s.io"]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["rbac.authorization.k8s.io"]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["apiextensions.k8s.io/v1beta1"]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["admissionregistration.k8s.io"]
            resources: ["*"]
            verbs: ["*"]
          - apiGroups: ["extensions/v1beta1"]
            resources: ["*"]
            verbs: ["*"]

required:
- name
- namespace
